name: create release

on:
  push:
    branches: [ master ]
    paths:
      - "**/workflows-trigger.properties"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "18"
          distribution: "oracle"
          architecture: x64

      - name: checkout
        uses: actions/checkout@v4

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: assembleRelease
        run: ./gradlew assembleRelease

      - name: get current time
        id: currentTime
        uses: josStorer/get-current-time@v2
        with:
          format: YYYY.MM.DD
          utcOffset: "+08:00"

      - name: create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"
          body: "create by workflows"
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: false
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ steps.currentTime.outputs.formattedTime }}
          name: v${{ steps.currentTime.outputs.formattedTime }}